from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics
from reportlab.lib.colors import HexColor
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT.parent.parent / "outputs" / "NexuFlow-1.7.0-Documentacao-Completa.pdf"
OUT.parent.mkdir(parents=True, exist_ok=True)

styles = getSampleStyleSheet()
styles.add(ParagraphStyle(name='Cover', parent=styles['Title'], fontName='Helvetica-Bold', fontSize=28, leading=34, alignment=TA_CENTER, textColor=HexColor('#F4F7FF'), spaceAfter=10))
styles.add(ParagraphStyle(name='CoverSub', parent=styles['Normal'], fontSize=13, leading=18, alignment=TA_CENTER, textColor=HexColor('#AFC8F5')))
styles.add(ParagraphStyle(name='H1x', parent=styles['Heading1'], fontName='Helvetica-Bold', fontSize=19, leading=23, textColor=HexColor('#153B72'), spaceBefore=8, spaceAfter=9))
styles.add(ParagraphStyle(name='H2x', parent=styles['Heading2'], fontName='Helvetica-Bold', fontSize=12.5, leading=16, textColor=HexColor('#166A8F'), spaceBefore=8, spaceAfter=5))
styles.add(ParagraphStyle(name='Bodyx', parent=styles['BodyText'], fontSize=9.2, leading=13.2, textColor=HexColor('#263447'), spaceAfter=5))
styles.add(ParagraphStyle(name='Smallx', parent=styles['BodyText'], fontSize=7.6, leading=10.5, textColor=HexColor('#536274')))
styles.add(ParagraphStyle(name='Callout', parent=styles['BodyText'], fontSize=9.1, leading=13, textColor=HexColor('#163B54'), backColor=HexColor('#E8F5FA'), borderColor=HexColor('#64B5D0'), borderWidth=0.7, borderPadding=8, spaceBefore=6, spaceAfter=8))
styles.add(ParagraphStyle(name='Footer', parent=styles['Normal'], fontSize=7.5, textColor=HexColor('#6A7788'), alignment=TA_CENTER))

def P(text, style='Bodyx'):
    return Paragraph(text, styles[style])

def bullets(items):
    return [P('&bull; ' + x, 'Bodyx') for x in items]

def table(headers, rows, widths=None):
    data = [[P(str(h), 'Smallx') for h in headers]] + [[P(str(c), 'Smallx') for c in r] for r in rows]
    t = Table(data, colWidths=widths, repeatRows=1, hAlign='LEFT')
    t.setStyle(TableStyle([
        ('BACKGROUND',(0,0),(-1,0),HexColor('#153B72')), ('TEXTCOLOR',(0,0),(-1,0),colors.white),
        ('GRID',(0,0),(-1,-1),0.35,HexColor('#C9D4E1')), ('VALIGN',(0,0),(-1,-1),'TOP'),
        ('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,HexColor('#F4F8FC')]), ('LEFTPADDING',(0,0),(-1,-1),6), ('RIGHTPADDING',(0,0),(-1,-1),6), ('TOPPADDING',(0,0),(-1,-1),5), ('BOTTOMPADDING',(0,0),(-1,-1),5)
    ]))
    return t

def footer(canvas, doc):
    canvas.saveState()
    canvas.setStrokeColor(HexColor('#D5DFEA')); canvas.line(18*mm, 14*mm, 192*mm, 14*mm)
    canvas.setFont('Helvetica', 7.5); canvas.setFillColor(HexColor('#6A7788'))
    canvas.drawString(18*mm, 9*mm, 'NexuFlow - Documentacao completa - 1.7.0 Insight Edition')
    canvas.drawRightString(192*mm, 9*mm, f'Pagina {doc.page}')
    canvas.restoreState()

def cover_footer(canvas, doc):
    canvas.saveState()
    canvas.setFillColor(HexColor('#071426'))
    canvas.rect(0, 0, A4[0], A4[1], fill=1, stroke=0)
    canvas.restoreState()
    footer(canvas, doc)

story=[]
story += [Spacer(1, 42*mm), P('NEXUFLOW', 'Cover'), P('Documentacao completa do projeto', 'CoverSub'), Spacer(1, 8*mm), P('Versao 1.7.0 - Insight Edition', 'CoverSub'), Spacer(1, 18*mm), P('Desempenho, diagnostico de latencia e seguranca para jogos competitivos no Windows.', 'CoverSub'), Spacer(1, 24*mm), P('Documento consolidado: recursos, arquitetura, protecoes, ping, Central do PC, historico de versoes, testes e limites conhecidos.', 'CoverSub'), PageBreak()]
story += [P('1. Visao geral', 'H1x'), P('O NexuFlow e uma plataforma local para entender e melhorar a experiencia de jogo no Windows sem promessas magicas. Ele mede qualidade de rede, saude do computador e oferece ajustes conservadores, reversiveis e condicionados ao jogo detectado.', 'Bodyx'), P('Principios do produto', 'H2x'), table(['Principio','Como aparece no aplicativo'],[
    ('Local-first','Dados, historico, desbloqueio cosmetico e relatorios ficam no computador.'),('Seguranca primeiro','Jogos protegidos entram em lockdown de compatibilidade; nao ha tentativa de burlar anticheat.'),('Medir antes de concluir','Ping, jitter, perda, picos e temperatura podem ficar desconhecidos quando nao ha dados suficientes.'),('Rollback','Mutacoes persistentes sao salvas em snapshots e restauradas ao parar, sair do jogo ou recuperar uma sessao interrompida.'),('Transparencia','A interface diferencia medicao, recomendacao, simulacao e validacao em partida real.')], [32*mm,138*mm]), Spacer(1,5*mm), P('O aplicativo nao instala driver proprio, nao intercepta trafego, nao injeta codigo, nao altera memoria de jogos e nao substitui uma rede global de relays.', 'Callout')]
story += [P('2. O que o aplicativo faz', 'H1x'), P('Navegacao principal', 'H2x'), table(['Area','Funcionalidades'],[
    ('Dashboard','Nexus Score, latencia, CPU/RAM/GPU, jogo atual e sinais de origem do lag.'),('Jogos','Catalogo de 10 jogos, descoberta local, busca, filtros, favoritos e politica de protecao.'),('Conexao','Monitor ao vivo, scanner neutro, DNS Lab, historico, comparacao e exportacao JSON.'),('Central do PC','Leituras de memoria, CPU, GPU/temperatura, Modo de Jogo e atalhos seguros do Windows.'),('Historico','Sessoes locais com perfil pedido/efetivo, antes/depois, saude do PC e eventos.'),('Investigador','Modo de transparencia para allowlist, estado, limites e relatorios.'),('Aparencia','Temas, alto contraste, escala de texto, movimento reduzido e Arte Secreta.'),('Ajustes','Preferencias, notificacoes, bandeja e comportamento do aplicativo.'),('Codigo secreto','Resgate local de NEXU-SECRETO-157, animacao, capa, mascote e audio.')], [32*mm,138*mm])]
story += [P('3. Sistema de ping e qualidade de rede', 'H1x'), P('O NexuFlow nao confunde um unico ping com a experiencia inteira. A janela de qualidade agrega latencia, jitter, perda de pacotes, picos, disponibilidade e um Nexus Score de 0 a 100. Perda recebe peso maior que pequenas diferencas de latencia.', 'Bodyx'), P('Monitor ao vivo', 'H2x'), *bullets(['Amostragem local aproximadamente a 1 Hz, sem interceptacao por pacote.', 'Janela de ate dois minutos, com mediana, minimo, maximo, p95, jitter e picos.', 'Timeouts e lacunas permanecem como ausencia de dado; nao sao convertidos em 0 ms.', 'Apos cinco segundos sem amostra, a leitura atual fica stale/desconhecida.', 'Quando a referencia muda, o grafico inicia um novo segmento para nao misturar destinos.']), P('Scanner neutro', 'H2x'), table(['Parametro','Comportamento'],[('Destinos','1.1.1.1, 8.8.8.8 e 9.9.9.9; lista fixa, sem alvo arbitrario.'),('Carga','12 sondas por destino, paralelas em grupos de 3; maximo de 36 consultas.'),('Timeout/intervalo','600 ms por sonda e 250 ms entre consultas.'),('Windows','ICMP nativo.'),('Outros sistemas','Fallback TCP/443, informado no resultado.'),('Conclusao','Referencias estaveis, divergencia, oscilacao compartilhada ou nenhuma resposta; nao culpa automaticamente o provedor.')], [38*mm,132*mm]), P('Importante: esse scanner mede a qualidade de referencias gerais da Internet. Ele nao le sockets do jogo e nao afirma ser o ping exato do servidor da partida.', 'Callout')]
story += [P('4. DNS Lab e diagnostico de rota', 'H1x'), P('O DNS Lab classifica Cloudflare, Google e Quad9 com dois servidores por provedor. Faz seis consultas UDP/53 por provedor a dominios publicos fixos (example.com, www.microsoft.com e www.cloudflare.com), calcula mediana e taxa de sucesso e exige pelo menos 75% de respostas para ser elegivel.', 'Bodyx'), P('Pontuacao: mediana + 150 ms x proporcao de falhas. Falha total gera resultado inconclusivo. O ranking nao troca o DNS, nao envia historico de navegacao e nao e uma recomendacao universal de privacidade.', 'Bodyx'), P('Diagnostico de rota usa ICMP proprio e TTL crescente para mostrar hops, latencia, jitter e perda aparente. Perda de ICMP em hop intermediario nao e prova de falha e nao dispara alteracao automatica.', 'Bodyx'), P('Historico e exportacao', 'H2x'), *bullets(['Ultimos dez scans ficam no armazenamento local.', 'Comparacao mostra a diferenca da mediana em relacao ao scan anterior comparavel; nao prova causalidade do BOOST.', 'Exportacao JSON inclui scan, ultimo ranking DNS e janela de monitoramento.', 'O diagnostico exportado nao e assinado; o relatorio de sessao assinado e separado.'])]
story += [P('5. Central do PC e desempenho', 'H1x'), P('A Central do PC prioriza observacao e orientacao. Ela nao promete FPS, porcentagens artificiais ou uma limpeza milagrosa.', 'Bodyx'), table(['Leitura/acao','Regra do produto'],[('CPU/RAM/GPU','Leituras reais quando disponiveis; sensor ausente aparece como indisponivel.'),('Alertas','RAM livre abaixo de 2 GB, CPU a partir de 85% e GPU a partir de 85 C viram sinais de atencao, nao diagnostico definitivo.'),('Modo de Jogo','Mostra preferencia e oferece atalho para a tela oficial do Windows.'),('Atalhos','Modo de Jogo, Capturas, Graficos, Inicializacao, Armazenamento, Energia e Rede via URIs ms-settings.'),('Preparar perfil','Seleciona o modo PC e abre o Dashboard; nao ativa BOOST sem clique.'),('Exclusoes','Nao limpa RAM compulsoriamente, nao desativa Windows Update/Defender, nao remove apps e nao altera boot.')], [38*mm,132*mm]), P('O BOOST pode aplicar ajustes gerais permitidos ao perfil, com snapshot e rollback. Perfis protegidos reduzem o escopo e mantem apenas operacoes externas ao processo do jogo.', 'Callout')]
story += [P('6. Modos de desempenho e BOOST', 'H1x'), table(['Modo','Escopo'],[('Ping','Qualidade de rede e ajustes de rede permitidos pelo lockdown.'),('PC','Desempenho geral reversivel do Windows.'),('Completo','Combinacao de Ping e PC.'),('Hardcore Safe','Somente leitura e relatorio.'),('Riot Safe / Valve Safe / Protected Safe / Unknown Safe','Camadas internas automaticas, nunca escolhidas diretamente pela WebView.')], [48*mm,122*mm]), P('Antes/depois', 'H2x'), *bullets(['O observer mantem uma baseline local de aproximadamente 20-30 segundos quando ha dados suficientes.', 'No cold start, aguarda amostras antes de mutar o Windows.', 'Ao parar, sair do jogo ou usar Restore All, o daemon desfaz mudancas na ordem segura.', 'Se a interface fechar, o daemon continua responsavel pela recuperacao da sessao armada.'])]
story += [P('7. Medidas de protecao e anti-cheat', 'H1x'), P('A politica e fail-closed: quando um jogo protegido e detectado, uma solicitacao agressiva e rebaixada automaticamente. O objetivo e minimizar interacao com anticheat, nunca esconder, enfraquecer ou contornar sua protecao.', 'Bodyx'), table(['Bloqueio','Aplicacao'],[('Processo/memoria','Nao le/escreve memoria, nao abre processo protegido para prioridade/CPU Sets, nao enumera modulos para inspecao.'),('Codigo/injecao','Sem DLL, hook grafico, overlay injetado ou automacao de input.'),('Rede do jogo','Sem sockets do jogo, interceptacao, modificacao, emulacao, redirecionamento ou firewall steering protegido.'),('Sistema','Sem pausar servicos anticheat, alterar arquivos do jogo, instalar driver ou desativar Trusted Mode.'),('Shell sensivel','PowerShell/pwsh e bloqueado durante sessoes protegidas; Windows Update de drivers e adiado.'),('Mutacoes','DNS, MTU, TCP experimental, standby purge e servicos ficam bloqueados durante gameplay protegido.')], [40*mm,130*mm]), P('Camadas de defesa: resolucao de perfil, gates do orquestrador, endpoints REST, guards de servico, managers de baixo nivel e auditoria estatica no build. Isso impede que um erro visual isolado habilite uma mutacao protegida.', 'Callout')]
story += [P('8. Catalogo de jogos e validacao', 'H1x'), table(['Jogo','Protecao/catalogacao'],[('Roblox','Perfil catalogado existente.'),('VALORANT','Riot Safe.'),('League of Legends','Riot Safe.'),('Counter-Strike 2','Valve Safe / Trusted Mode preservado.'),('Fortnite','Perfil protegido conservador; EAC/BattlEye catalogado.'),('Fall Guys','EAC catalogado.'),('PUBG: BATTLEGROUNDS','BattlEye catalogado.'),('Rainbow Six Siege','BattlEye catalogado.'),('DayZ','BattlEye catalogado.'),('Arma 3','BattlEye catalogado.')], [55*mm,115*mm]), P('A descoberta usa nomes de executaveis e bibliotecas Steam conhecidas. Para os seis jogos adicionados, os testes automatizados validam catalogo, aliases, politicas e bloqueios. Ainda nao ha validacao em partidas reais nem certificacao dos fornecedores; patches podem alterar executaveis.', 'Callout')]
story += [P('9. Privacidade, rede e arquitetura', 'H1x'), P('A regra estrutural de rede e negar por padrao. A interface fala com o motor local em 127.0.0.1. Sondas e DNS Lab usam somente os destinos fixos documentados e nao enviam telemetria externa obrigatoria, anuncios, login ou comando remoto.', 'Bodyx'), table(['Camada','Responsabilidade'],[('Angular WebView','Interface sem privilegio administrativo; nao executa comandos genericos.'),('Tauri Rust','Allowlist de comandos, cache de telemetria e registro de acoes.'),('Observer Python','Leitura persistente e nao privilegiada; sem mutacoes.'),('Helper/daemon','Solicita UAC somente para mutacoes estreitas e mantem rollback.'),('Estado','Snapshots em %PROGRAMDATA%\\NexuFlow\\state; historico em %LOCALAPPDATA%\\NexuFlow\\history.')], [42*mm,128*mm]), P('O aplicativo instalado nao precisa manter VS Code, Node dev server ou FastAPI abertos.', 'Bodyx')]
story += [P('10. Aparencia e Arte Secreta', 'H1x'), *bullets(['Temas publicos: Nebula, Midnight, Emerald, Alto Contraste, Blocos, Reliquia, Tatico e Operacao.', 'Acessibilidade: escala de texto, movimento reduzido, alto contraste, nomes acessiveis e navegação compacta.', 'Arte Secreta e apenas cosmetica: desbloqueio local, capa, icone e mascote; nao altera motor, rede ou anticheat.', 'Codigo: NEXU-SECRETO-157. RESET-CODIGOS remove o resgate local para testes.', 'Apos novo resgate bem-sucedido, a animacao mostra a recompensa e toca uma vez o MP3 fornecido pelo usuario.', 'Audio local empacotado em public/theme-art/secret/secret-unlock.mp3, sem download, sem loop, volume de 70%, com silenciar e retry manual se autoplay for bloqueado.', 'O audio nao toca com codigo invalido, abertura do app, troca de tema ou resgate ja usado.']), P('O arquivo de audio distribuido tem 95.956 bytes e SHA-256 fad3ff185e15bf42afef82942faad96db44186178b734847a26e80fcc4998ac0.', 'Smallx')]
story += [P('11. Historico de versoes', 'H1x'), table(['Versao','Principais entregas'],[('1.2-1.4','Base do BOOST, modos, rollback, diagnosticos e primeiras politicas de seguranca.'),('1.5 / 1.5.5','Trust Edition, Driver Center manual, allowlist e relatorios.'),('1.5.7','Galeria de aparencia, temas originais e acessibilidade visual.'),('1.5.8 / 1.5.9','Arte Secreta, codigo local, capa, mascote e refinamento visual.'),('1.6 / 1.6.1','Investigador, bandeja, melhorias de rollback, interface e correcoes de acessibilidade.'),('1.7.0','Insight Edition: Central de Conexao, DNS Lab, Central do PC, catalogo de 10 jogos, favoritos, historico/exportacao e audio da Arte Secreta.')], [34*mm,136*mm])]
story += [P('12. Testes, build e limites', 'H1x'), P('Fechamento local da 1.7.0', 'H2x'), *bullets(['214 testes Python/API/engine aprovados.', '20 testes Angular da interface aprovados.', '1 teste Rust de shutdown seguro aprovado no alvo de biblioteca.', 'Auditoria estatica anti-cheat, contrato sem driver, allowlist de rede e manifesto/SBOM aprovados.', 'Build Tauri/NSIS x64 e pacote fonte deterministico gerados.', 'Audio conferido byte a byte no pacote fonte.']), P('O que ainda exige verificacao antes de distribuicao comercial', 'H2x'), *bullets(['Smoke test em Windows 10 e 11 limpos, instalacao, desinstalacao, UAC e encerramento inesperado.', 'Teste com adaptadores Intel, Realtek e Wi-Fi e com atualizacoes opcionais reais.', 'Teste com versoes atuais de VALORANT, LoL, CS2 e ao menos um titulo EAC/BattlEye.', 'Assinatura Authenticode comercial e nova revisao das politicas oficiais dos anticheats.', 'Validacao em partidas reais dos seis jogos novos.']), P('Limites honestos', 'H2x'), P('O NexuFlow nao garante reducao de ping, FPS maior, ausencia de banimento, compatibilidade futura com qualquer patch ou limite fixo de memoria. Ele mede, explica, recomenda e reverte dentro do escopo documentado.', 'Callout'), P('Referencias do proprio projeto: docs/RELEASE_1.7.md, docs/COMPETITOR_REVIEW_1.7.md, docs/NETWORK_QUALITY.md, docs/NETWORK_ALLOWLIST.md, docs/PERFORMANCE.md, docs/ANTI_CHEAT.md, docs/SAFETY.md, docs/ARCHITECTURE.md, docs/VALIDATION.md e docs/SECRET_AUDIO_ASSET.md.', 'Smallx')]

doc = SimpleDocTemplate(str(OUT), pagesize=A4, rightMargin=18*mm, leftMargin=18*mm, topMargin=17*mm, bottomMargin=19*mm, title='NexuFlow - Documentacao completa 1.7.0', author='NexuFlow')
doc.build(story, onFirstPage=cover_footer, onLaterPages=footer)
print(OUT)
